meta_columns:
  - patch_idx
  - barcode
  - color_path
  - gray_path
  - mask_path
  - sample_id
  - label
  - target_label

target_column: target_label

exclude_columns: []

exclude_prefixes:
  - diagnostics_

binary_indicator:
  positive:
    - "1"
    - "true"
    - "yes"
    - "y"
    - "t"
  negative:
    - "0"
    - "false"
    - "no"
    - "n"
    - "f"

column_types:
  numerical:
    include_prefixes:
      - original_
      - squareroot_
      - logarithm_
      - wavelet-
      - exponential_
      - square_
      - log-sigma-
    include_columns: []
    exclude_columns: []

  binary:
    include_columns: []
    exclude_columns: []

  categorical:
    include_columns: []
    exclude_columns: []

preprocessing:
  lowercase_columns: true
  fill_missing_numerical: mode
  fill_missing_categorical: mode
  fill_missing_binary: mode
  scale_numerical: true
  scaler: minmax
  encode_categorical: false